/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/andre/root/_local/anlogic_td/test_prj/al_ip/ip_dsp.v
 ** Date	:	2019 09 01
 ** TD version	:	4.3.815
\************************************************************/

`timescale 1ns / 1ps

module oc_dsp ( p, a, b, cea, ceb, cepd, clk, rstan, rstbn, rstpdn );

	output [35:0] p;

	input  [17:0] a;
	input  [17:0] b;
	input  cea;
	input  ceb;
	input  cepd;
	input  clk;
	input  rstan;
	input  rstbn;
	input  rstpdn;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(18),
				.INPUT_WIDTH_B(18),
				.OUTPUT_WIDTH(36),
				.INPUTFORMAT("SIGNED"),
				.INPUTREGA("ENABLE"),
				.INPUTREGB("ENABLE"),
				.OUTPUTREG("ENABLE"),
				.IMPLEMENT("AUTO"),
				.SRMODE("ASYNC")

			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(cea),
				.ceb(ceb),
				.cepd(cepd),
				.clk(clk),
				.rstan(rstan),
				.rstbn(rstbn),
				.rstpdn(rstpdn)
			);


endmodule