/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/andre/root/_local/anlogic_td/test_prj/al_ip/ip_lutfifo.v
 ** Date	:	2019 09 02
 ** TD version	:	4.4.433
\************************************************************/

`timescale 1ns / 1ps

module ip_lutfifo (
	rst,
	di, clkr, re, clkw, we,
	do,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [7:0] di;
	input clkw, we;
	input clkr,re;

	output [7:0] do;
	output empty_flag;
	output full_flag;
	output [8:0] rdusedw;
	output [8:0] wrusedw;

EG_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(8),
	.ADDR_WIDTH(8),
	.SHOWAHEAD(1)
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.do(do),
	.clkr(clkr),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule