/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/andre/root/_local/anlogic_td/test_prj/al_ip/ip_oc_osc.v
 ** Date	:	2019 09 01
 ** TD version	:	4.3.815
\************************************************************/

`timescale 1ns / 1ps

module oc_osc ( osc_dis, osc_clk );
	output 		 osc_clk;
	input  		 osc_dis;

		EG_PHY_OSC #(
		.STDBY("DISABLE"))
		inst(
		.osc_clk(osc_clk),
		.osc_dis(osc_dis));

endmodule