/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/andre/root/_local/anlogic_td/test_prj/al_ip/ip_oc_adc.v
 ** Date	:	2019 09 01
 ** TD version	:	4.3.815
\************************************************************/

`timescale 1ns / 1ps

module oc_adc ( eoc, dout, clk, pd, s, soc );
	output 		 eoc;
	output  		[11:0] dout;

	input  		clk;
	input  		pd;
	input  		[2:0] s;
	input  		soc;

	EG_PHY_ADC #(
		.CH7("ENABLE"),
		.CH6("ENABLE"),
		.CH5("ENABLE"),
		.CH4("ENABLE"),
		.CH3("ENABLE"),
		.CH2("ENABLE"),
		.CH1("ENABLE"),
		.CH0("ENABLE"))
		adc (
		.clk(clk),
		.pd(pd),
		.s(s),
		.soc(soc),
		.eoc(eoc),
		.dout(dout));

endmodule